Console.WriteLine("The Tech Academy");
Console.WriteLine("The Current Time is " + DateTime.Now);
Console.WriteLine("Student Daily Report");
Console.WriteLine("Name?");
Console.WriteLine("Course?");
Console.WriteLine("Page?");
Console.WriteLine("Do you need help?");
Console.WriteLine("Positive experiences?");
Console.WriteLine("Feedback?");
Console.WriteLine("Hours studied?");
Console.WriteLine("Thank you!");
